# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
    - ImageHash==4.3.1            # https://github.com/JohannesBuchner/imagehash
    - diffimg==0.3.0              # https://github.com/nicolashahn/diffimg
    - scikit-image==0.22.0
    - matplotlib==3.8.2
    - pandas==2.2.0
    - imageio==2.33.1
